# Generated by Django 4.2.16 on 2024-12-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationShow',
        ),
    ]
