# Generated by Django 4.2.16 on 2024-12-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationshow',
            name='month',
            field=models.SmallIntegerField(max_length=2),
        ),
    ]
