# Generated by Django 4.2.16 on 2024-11-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(max_length=2)),
                ('month', models.SmallIntegerField(max_length=2)),
                ('year', models.SmallIntegerField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
            options={
                'db_table': 'notificationsshow',
            },
        ),
    ]
